author: notquiteamonad
bug-reports: "https://github.com/notquiteamonad/prompt-hs/issues"
category: CLI
dependencies:
  - base >= 4.14.3.0 && < 5
  - microlens >= 0.4.0.1 && < 0.5
  - terminal >= 0.2 && < 0.3
  - text >= 1.2.4.1 && < 2.2
description: |
  A library making use of the terminal package to prompt users for answers in a CLI context.

  Supports freeform text as well as choices between sum type constructors.
flags:
  prod:
    default: false
    description: Enable production defaults
    manual: true
ghc-options:
- -Wall
- -Wcpp-undef
- -Widentities
- -Wincomplete-patterns
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-deriving-strategies
- -Wmissing-export-lists
- -Wmissing-import-lists
- -Wmissing-signatures
- -Wpartial-fields
- -Wredundant-constraints
homepage: "https://github.com/notquiteamonad/prompt-hs"
library:
  dependencies: []
  source-dirs: src
license: BSD-3-Clause
name: prompt-hs
synopsis: A user-friendly, dependently-typed library for asking your users questions
tested-with:
  - GHC == 8.10.7
  - GHC == 9.0.2
  - GHC == 9.2.8
  - GHC == 9.4.8
  - GHC == 9.6.6
  - GHC == 9.8.4
version: 1.0.0.0
when:
- condition: flag(prod)
  ghc-options:
  - -O2
  - -Werror
